<a href="https://colab.research.google.com/github/sreyaad/ANN-Iris/blob/main/ANN_Iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Importing Packages
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Dense
from sklearn import datasets

In [ ]:
data=datasets.load_iris()
print(data)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [ ]:
x=data.data
y=data.target
z=data.target_names
print(data.feature_names)
print(x[0])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
[5.1 3.5 1.4 0.2]


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [ ]:
print(x_train.shape)
print(x_test.shape)

(105, 4)
(45, 4)


In [ ]:
#Building the Model
model=Sequential();
model.add(Dense(100,input_shape=(4,),activation="relu"))
model.add(Dense(3,activation="softmax"))

In [ ]:
#compile model
model.compile(optimizer="sgd",loss="sparse_categorical_crossentropy",metrics=["accuracy"])

In [ ]:
#Fit the model
model.fit(x_train,y_train,epochs=20)

Epoch 1/20
4/4 [==============================] - 0s 2ms/step - loss: 1.2291 - accuracy: 0.3143
Epoch 2/20
4/4 [==============================] - 0s 2ms/step - loss: 1.0163 - accuracy: 0.4000
Epoch 3/20
4/4 [==============================] - 0s 2ms/step - loss: 0.9430 - accuracy: 0.7429
Epoch 4/20
4/4 [==============================] - 0s 3ms/step - loss: 0.8946 - accuracy: 0.8000
Epoch 5/20
4/4 [==============================] - 0s 2ms/step - loss: 0.8405 - accuracy: 0.8095
Epoch 6/20
4/4 [==============================] - 0s 2ms/step - loss: 0.8054 - accuracy: 0.8286
Epoch 7/20
4/4 [==============================] - 0s 3ms/step - loss: 0.7812 - accuracy: 0.7714
Epoch 8/20
4/4 [==============================] - 0s 1ms/step - loss: 0.7560 - accuracy: 0.7810
Epoch 9/20
4/4 [==============================] - 0s 2ms/step - loss: 0.7280 - accuracy: 0.7619
Epoch 10/20
4/4 [==============================] - 0s 1ms/step - loss: 0.7057 - accuracy: 0.7905
Epoch 11/20
4/4 [======================

In [ ]:
#Evaluate the Model
model.evaluate(x_test,y_test)

2/2 [==============================] - 0s 5ms/step - loss: 0.5574 - accuracy: 0.9778


[0.5574156641960144, 0.9777777791023254]

In [ ]:
pred=model.predict(x_test[:10])
print(pred)

[[0.07413512 0.41515583 0.51070905]
 [0.0492816  0.3855266  0.5651918 ]
 [0.25516987 0.46352482 0.28130528]
 [0.16338877 0.4596562  0.37695503]
 [0.07480722 0.39890772 0.52628505]
 [0.18817613 0.48503128 0.3267926 ]
 [0.16629322 0.44193223 0.3917746 ]
 [0.05793526 0.3569234  0.5851413 ]
 [0.7379566  0.18668893 0.07535441]
 [0.7100964  0.20353399 0.08636955]]


In [ ]:
p=np.argmax(pred,axis=1)
print(p)
print(y_test[:10])

[2 2 1 1 2 1 1 2 0 0]
[2 2 1 1 2 1 1 2 0 0]


In [ ]:
for i in p:
  print("Predicted Class:{}, Name:{}".format(i,z[i]))

Predicted Class:2, Name:virginica
Predicted Class:2, Name:virginica
Predicted Class:1, Name:versicolor
Predicted Class:1, Name:versicolor
Predicted Class:2, Name:virginica
Predicted Class:1, Name:versicolor
Predicted Class:1, Name:versicolor
Predicted Class:2, Name:virginica
Predicted Class:0, Name:setosa
Predicted Class:0, Name:setosa
